spring.application.name=modern-java-sandbox
spring.threads.virtual.enabled=true
# Force Hibernate to automatically create/update database tables from JPA entities
spring.jpa.hibernate.ddl-auto=update

# Optional: Disable the Open Session in View warning logged earlier
spring.jpa.open-in-view=false